name: Mantener activo Supabase

on:
  schedule:
    - cron: '0 15 */3 * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Pedido al proyecto de Supabase
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" -H "apikey: sb_publishable_AxAAi6LMTk6_A7JgyLK5BA_ArMtOaG4" "https://qfbskivafuungzdfzggv.supabase.co/auth/v1/health"
